
// If set in opcode.flags, the last argument to this opcode is a reference to
// a code location that the instruction can jump to (ie. it's a goto-type
// instruction):
#define OPCODE_LOCATION_REF  0x01

// If set in opcode.flags, this is a "terminal" instruction and we should not
// decode any subsequent ones.
#define OPCODE_TERMINAL      0x02

struct acs_opcode {
	const char *name;
	int nargs;
	int flags;
};

const struct acs_opcode acs_opcodes[] = {
	{"NOP",                  0, 0},
	{"Terminate",            0, OPCODE_TERMINAL},
	{"Suspend",              0, 0},
	{"PushNumber",           1, 0},
	{"LSpec1",               1, 0},
	{"LSpec2",               1, 0},
	{"LSpec3",               1, 0},
	{"LSpec4",               1, 0},
	{"LSpec5",               1, 0},
	{"LSpec1Direct",         2, 0},
	{"LSpec2Direct",         3, 0},
	{"LSpec3Direct",         4, 0},
	{"LSpec4Direct",         5, 0},
	{"LSpec5Direct",         6, 0},
	{"Add",                  0, 0},
	{"Subtract",             0, 0},
	{"Multiply",             0, 0},
	{"Divide",               0, 0},
	{"Modulus",              0, 0},
	{"EQ",                   0, 0},
	{"NE",                   0, 0},
	{"LT",                   0, 0},
	{"GT",                   0, 0},
	{"LE",                   0, 0},
	{"GE",                   0, 0},
	{"AssignScriptVar",      1, 0},
	{"AssignMapVar",         1, 0},
	{"AssignWorldVar",       1, 0},
	{"PushScriptVar",        1, 0},
	{"PushMapVar",           1, 0},
	{"PushWorldVar",         1, 0},
	{"AddScriptVar",         1, 0},
	{"AddMapVar",            1, 0},
	{"AddWorldVar",          1, 0},
	{"SubScriptVar",         1, 0},
	{"SubMapVar",            1, 0},
	{"SubWorldVar",          1, 0},
	{"MulScriptVar",         1, 0},
	{"MulMapVar",            1, 0},
	{"MulWorldVar",          1, 0},
	{"DivScriptVar",         1, 0},
	{"DivMapVar",            1, 0},
	{"DivWorldVar",          1, 0},
	{"ModScriptVar",         1, 0},
	{"ModMapVar",            1, 0},
	{"ModWorldVar",          1, 0},
	{"IncScriptVar",         1, 0},
	{"IncMapVar",            1, 0},
	{"IncWorldVar",          1, 0},
	{"DecScriptVar",         1, 0},
	{"DecMapVar",            1, 0},
	{"DecWorldVar",          1, 0},
	{"Goto",                 1, OPCODE_LOCATION_REF|OPCODE_TERMINAL},
	{"IfGoto",               1, OPCODE_LOCATION_REF},
	{"Drop",                 0, 0},
	{"Delay",                0, 0},
	{"DelayDirect",          1, 0},
	{"Random",               0, 0},
	{"RandomDirect",         2, 0},
	{"ThingCount",           0, 0},
	{"ThingCountDirect",     2, 0},
	{"TagWait",              0, 0},
	{"TagWaitDirect",        1, 0},
	{"PolyWait",             0, 0},
	{"PolyWaitDirect",       1, 0},
	{"ChangeFloor",          0, 0},
	{"ChangeFloorDirect",    2, 0},
	{"ChangeCeiling",        0, 0},
	{"ChangeCeilingDirect",  2, 0},
	{"Restart",              0, OPCODE_TERMINAL},
	{"AndLogical",           0, 0},
	{"OrLogical",            0, 0},
	{"AndBitwise",           0, 0},
	{"OrBitwise",            0, 0},
	{"EorBitwise",           0, 0},
	{"NegateLogical",        0, 0},
	{"LShift",               0, 0},
	{"RShift",               0, 0},
	{"UnaryMinus",           0, 0},
	{"IfNotGoto",            1, OPCODE_LOCATION_REF},
	{"LineSide",             0, 0},
	{"ScriptWait",           0, 0},
	{"ScriptWaitDirect",     1, 0},
	{"ClearLineSpecial",     0, 0},
	{"CaseGoto",             2, OPCODE_LOCATION_REF},
	{"BeginPrint",           0, 0},
	{"EndPrint",             0, 0},
	{"PrintString",          0, 0},
	{"PrintNumber",          0, 0},
	{"PrintCharacter",       0, 0},
	{"PlayerCount",          0, 0},
	{"GameType",             0, 0},
	{"GameSkill",            0, 0},
	{"Timer",                0, 0},
	{"SectorSound",          0, 0},
	{"AmbientSound",         0, 0},
	{"SoundSequence",        0, 0},
	{"SetLineTexture",       0, 0},
	{"SetLineBlocking",      0, 0},
	{"SetLineSpecial",       0, 0},
	{"ThingSound",           0, 0},
	{"EndPrintBold",         0, 0},
};
