name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Install build dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt -q install libncurses-dev gcc make libaudiofile-dev

    - uses: actions/checkout@v4

    - name: make
      run: make -j8 -k
